services:
  # --- BACKUP DATABASE (opzionale) ---
  backup:
    build:
      context: ./backup
    container_name: skeletron_apache_backup
    env_file:
      - .env
    volumes:
      - ./backups:/backups
    networks:
      - default
