services:
  # --- SITO WEB ---
  app:
    build: .
    container_name: skeletron_apache_app
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./www:/var/www/html/
    env_file:
      - .env
    networks:
      - default

  # --- DATABASE ---
  db:
    image: mariadb:latest
    container_name: skeletron_apache_db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./skeletron_apache.sql:/docker-entrypoint-initdb.d/skeletron_apache.sql
    networks:
      - default

networks:
  web_network:
    external: true

volumes:
  db_data:
